
networks:
  wage-cloud: 
    name: wage-cloud

services:
  postgres:
    container_name: wage-cloud-db
    image: postgres:13
    restart: on-failure:3
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: wage
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: wage_cloud
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - wage-cloud



volumes:
  postgres-data:

