networks:
  wagecloud-network:
    name: wagecloud-network
    external: false

services:
  postgres:
    container_name: wagecloud-postgres
    image: postgres:latest
    ports:
      - "5433:5432"
    expose:
      - "5433"
    environment:
      POSTGRES_USER: wagecloud
      POSTGRES_PASSWORD: wagecloud
      POSTGRES_DB: wagecloud
    volumes:
      - wagecloud-data:/var/lib/postgresql/data
    networks:
      - wagecloud-network
volumes:
  wagecloud-data:
