networks:
  wagecloud-network:
    name: wagecloud-network
    external: false

volumes:
  wagecloud-postgres-data:
  wagecloud-redis-data:
  wagecloud-nats-data:


services:
  postgres:
    container_name: wagecloud-postgres
    image: postgres:17-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: wagecloud
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-peakwagecloudpassword}
      POSTGRES_DB: wagecloud
    volumes:
      - wagecloud-postgres-data:/var/lib/postgresql/data
    networks:
      - wagecloud-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U wagecloud -d wagecloud" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  redis:
    container_name: wagecloud-redis
    image: redis:8-alpine
    ports:
      - "6379:6379"
    volumes:
      - wagecloud-redis-data:/data
    networks:
      - wagecloud-network
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-peakwagecloudpassword}
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  nats:
    container_name: wagecloud-nats
    image: nats:2.11-alpine
    ports:
      - "4222:4222" # Client connections
      - "8222:8222" # HTTP monitoring
    networks:
      - wagecloud-network
    volumes:
      - wagecloud-nats-data:/data
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8222/healthz" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
