# Example configuration file - Copy this to config.yml and fill in your values

env: "dev" # Available options: dev, staging, production

app:
  decimals: 9 # Max decimals for handling float number
  accessTokenDuration: 86400 # 1 day
  refreshTokenDuration: 604800 # 7 days
  baseImageDir: "/path/to/base/images/"
  vmImageDir: "/path/to/vm/images/"
  cloudinitDir: "/path/to/cloudinit/"

httpServer:
  port: 9005

log:
  level: "debug" # debug, info, warn, error, dpanic, panic, fatal
  stacktraceLevel: "error"
  fileEnabled: false
  fileSize: 10 # MB
  filePath: "log/log.log"
  fileCompress: false # enable log file compress before rotate
  maxAge: 1 # days to keep log files
  maxBackups: 10 # number of log files

postgres:
  url: "" # Optional: full connection URL
  host: "localhost"
  port: "5432"
  database: "dbname"
  username: "username"
  password: "password"
  maxConnections: 8
  maxIdleConnections: 10
  logQuery: false

s3:
  accessKeyID: "your_access_key_id"
  secretAccessKey: "your_secret_access_key"
  region: "your_region"
  bucket: "your_bucket_name"
  cloudfrontUrl: "your_cloudfront_url"

# Redis configuration (uncomment if needed)
#redis:
#  - host: "localhost"
#    port: 6379
#    password: ""
#    db: 0

sentry:
  dsn: "your_sentry_dsn"
  environment: "DEV"
  release: ""
  debug: false

scheduler:
  timezone: "Asia/Bangkok"

sensitiveKeys:
  jwtSecret: "your_jwt_secret"
  pepper: "your_pepper"
  encryptionKey: "your_encryption_key"
  iterations: 150000

vnpay:
  tmnCode: "your_tmn_code"
  hashSecret: "your_hash_secret"